name: Ci

on:
  workflow_dispatch
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install client dependencies
        working-directory: client
        run: npm install  
      - name: run client tests
        working-directory: client
        run: npm test
      - name: install server dependencies
        working-directory: server
        run: npm install
      - name: run server tests
        working-directory: server
        run: npm test
      
